Repository KaranSinghBisht/Space-Frontend, pull requests merged in 2020-10, with the labels that each got.

#8 Contributing md tomassirio
  CONTRIBUTING.es.md
  CONTRIBUTING.md
  README.md
Labels: Hacktoberfest Accepted

#12 Add prettier to project
  front-end/.gitignore
  front-end/.prettierrc.json
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/App.jsx
  front-end/src/index.jsx
Labels: Hacktoberfest Accepted

#14 Add react footer component
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.jsx
  front-end/src/components/Button/Button.module.css
  front-end/src/components/Button/index.jsx
  front-end/src/components/Footer/Footer.module.css
  front-end/src/components/Footer/index.jsx
  front-end/src/components/Icon/Icon.module.css
  front-end/src/components/Icon/index.jsx
  front-end/src/components/IconGroup/IconGroup.module.css
  front-end/src/components/IconGroup/index.jsx
  front-end/src/components/IconLink/IconLink.module.css
  front-end/src/components/IconLink/index.jsx
  front-end/src/components/Input/Input.module.css
  front-end/src/components/Input/index.jsx
  front-end/src/components/RegisterNewsletter/RegisterNewsletter.module.css
  front-end/src/components/RegisterNewsletter/index.jsx
  front-end/src/styles/variables.css
Labels: Hacktoberfest Accepted

#15 Adding Logo
  front-end/public/LogoPng.png
  front-end/public/LogoSvg.svg
Labels: Hacktoberfest Accepted, hacktoberfest-accepted

#17 Changes
  front-end/package-lock.json
  front-end/package.json
  front-end/public/index.html
  front-end/src/App.jsx
  front-end/src/Nav/Nav.js
  front-end/src/Nav/Nav.style.css
  front-end/src/Nav/NavItems.js
Labels: hacktoberfest-accepted

#18 Add react router dom
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.jsx
  front-end/src/index.jsx
  front-end/src/layouts/DefaultLayout/DefaultLayout.module.css
  front-end/src/layouts/DefaultLayout/index.jsx
  front-end/src/pages/explore/index.jsx
  front-end/src/pages/forum/index.jsx
  front-end/src/pages/home/index.jsx
Labels: hacktoberfest-accepted

#19 Add header with navigation
  front-end/package-lock.json
  front-end/src/App.jsx
  front-end/src/components/Header/Header.module.css
  front-end/src/components/Header/index.jsx
  front-end/src/components/Navigation/Navigation.module.css
  front-end/src/components/Navigation/index.jsx
  front-end/src/components/NavigationLink/NavigationLink.module.css
  front-end/src/components/NavigationLink/index.jsx
  front-end/src/layouts/DefaultLayout/index.jsx
Labels: hacktoberfest-accepted

#28 docs: Additional instructions for setting up dev environment
  CONTRIBUTING.md
Labels: hacktoberfest-accepted
